// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id:
    'us-east-1:90dc4a93-37de-407c-901a-92ca755ec2e3',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_jTmnvkpVE',
  aws_user_pools_web_client_id: '5vfbo6c8r0d38tq54pbcs9junr',
  oauth: {},
  aws_user_files_s3_bucket: 'testing54920-dev',
  aws_user_files_s3_bucket_region: 'us-east-1',
};

export default awsmobile;
